modLoader = "javafml"
loaderVersion = "[41,)"
issueTrackerURL = "https://github.com/Frinn38/Infinite-Music/issues"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_title}"
authors = "${mod_author}"
description = '''
${mod_description}
'''
logoFile = "icon.png"

[[dependencies.infinitemusic]]
modId = "forge"
mandatory = true
versionRange = "[41,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.infinitemusic]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.infinitemusic]]
modId = "architectury"
mandatory = true
versionRange = "[5.5.18,)"
ordering = "AFTER"
side = "BOTH"